### ISSUE TITLE
Late:Enhancement: Push Profile and Prefences Plugin

### ISSUE THREAD

**Issue by KipOmaha** [KipOmaha/Dashboard#25]
A plugin for your personal info.

**Comment by KipOmaha** [comment]
@csuwildcat if you don't mind, what do you think of this idea?  

1.  Form would be able to read information via xml or json file 
2.  Users could fill out the form and instead of saving it via of php submission or other submission
they could save it as a json or xml and keep their info and preferences on a usb or other local disk.
3. The component flex application could be served like a static html page and wait for users to interact with the page.

**Comment by csuwildcat** [comment]
Not sure I understand what the component would be/look like - do you have more details?

**Comment by KipOmaha** [comment]
1. A normal CMS would have something like => header => main conent => footer
and maybe some widgets that you can customize with the front-end. 
  =>  Localities and ideas on the web aren't always so simple
2.  The Front-end that a CMS provides is a static form that reflects the servers setup. It sort of conflicts with a fluid and growing web standard => I mean it writes its own and expects you to follow it.

This creates problems where users are stuck in not only design but with how there identity is kept on the web.

When signing up your stuck with your info on the server even if you made a mistake.

I believe that a custom web component can be built that allows developers to easily switch from web server application logic to a local browser scope and than allow users...after giving a user an ample amount of time to really get there profile information done to than upload it.  

______________________________________________________________________________________________________________
1. Sum it up: A basic web application dashboard should contain a profiling machine that allows users to save locally and upload there profile info when they are sure that the information is 100%.
______________________________________________________________________________________________________________

1. Component should come with UI template parts for adding lines/multiline  inputs
2. Ability to label added lines
3. Component should come with UI template parts for adding Boolean value inputs
4. Ability to label Boolean inputs
5. A save locally button template part
6. A submit post button template part
7. Upload Profile button template part

**Comment by KipOmaha** [comment]
so the look would sort of be like a google form.

But with different upload options
