### ISSUE TITLE
Enhancement: LotusJS pollyfill

### ISSUE THREAD

**Issue by KipOmaha** [KipOmaha/Dashboard#30]
Going to depreciate the use of custom elements for the Hobby Shop Dashboard build at least, and use the typescript based LotusJS which uses the x-tag V1 library for component mapping. 

Advantages: 
1. Open Space for components, so components built can be shared both on Bower and LotusJS
2. LotusJS uses Typescript which is supported by Microsoft and is a first class transpiler technology.
3. ES6 is acceptable in LotusJS
4. Decouple the mapped component and the DOM allows you to code and try out new art and design concepts freely.

@doriansmiley, @csuwildcat , any input would be helpful if either of you have time.

**Comment by doriansmiley** [comment]
@KipOmaha I'm working on some changes to Lotus that will enable code splitting. Right now there are a lot of dependencies on LavenderJS which is a micro architecture that contains a lot of common utilities such as Matrix/Path utils, observable implementations, etc. The way the code is included though needs to change. You'll notice in the source there are imports in the following form:
````
import * as Lavender from 'lavenderjs/lib';
````
This has the effect of importing the entire lib into the resulting code. This is avoided by the following webpack config:
````
externals: {
        "lavenderjs/lib": "Lavender"
    },
````
This tells the compiler to ignore imports in the resulting compiled javascript. This is a common technique if you plan to use UMD modules included with a `<script>` tag, but it's not good for using ES6 module imports. I plan to refactor Lotus to not use this import form and rely on tree shaking to avoid duplicate code. This will result in a compiled Lib that contains all the Lavender dependencies included. This will require all future projects use TypeScript as their source to avoid duplicate code. If you are working on a project that uses TypeScript be sure to avoid the above style import for Lotus elements. Be sure to use a standard import such as:
````
import {AbstractThumbnailView} from "./AbstractThumbnailView";
````
This will future proof your code. You can still use Lotus in a pure Javascript implementation just be aware that in a future release you may wind up with duplicate code if you also include the Lavender lib using a script tag.

**Comment by KipOmaha** [comment]
Thanks @doriansmiley, I'll get into these changes tonight, I'm off to work soon atm.  

Typescript, seems to be pulling me over their way. Thanks for the info, good to know for future components.
